export const REGISTER_SUCCESS="REGISTER_SUCCESS";
export  const REGISTER_FAILED="REGISTER_FAILED";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_FAILED="LOGIN_FAILED";
export const LOAD_SUCCESS="LOAD_SUCCESS";
export const LOAD_FAILED="LOAD_FAILED";
export const LOAD_ALL_USERS_SUCCESS="LOAD_ALL_USERS_SUCCESS";
export const LOAD_ALL_USERS_FAILED="LOAD_ALL_USERS_FAILED";
export const LOGOUT="LOGOUT";
export const ADD_SUCCESS="ADD_SUCCESS";
export const ADD_FAILED="ADD_FAILED";
export const EDIT_PROFIL_SUCCESS="EDIT_PROFIL_SUCCESS";
export const EDIT_PROFIL_FAILED="EDIT_PROFIL_FAILED";
export const DELETE_USER_SUCCESS="DELETE_USER_SUCCESS";
export const DELETE_USER_FAILED="DELETE_USER_FAILED";
export const LOAD_USER_SUCCESS="LOAD_USER_SUCCESS";
export const LOAD_USER_FAILED="LOAD_USER_FAILED";
//////////projecttypes///////////
export const LOAD_PROJECT_SUCCESS="LOAD_PROJECT_SUCCESS";
export const LOAD_PROJECT_FAILED="LOAD_PROJECT_FAILED";
export const ADD_PROJECT_SUCCESS="ADD_PROJECT_SUCCESS";
export const ADD_PROJECT_FAILED="ADD_PROJECT_FAILED";
export const EDIT_PROJECT_SUCCESS="EDIT_PROJECT_SUCCESS";
export const EDIT_PROJECT_FAILED="EDIT_PROJECT_FAILED";
export const DELETE_PROJECT_SUCCESS="DELETE_PROJECT_SUCCESS";
export const DELETE_PROJECT_FAILED="DELETE_PROJECT_FAILED";
export const LOAD_ONE_PROJECT_SUCCESS="LOAD_ONE_PROJECT_SUCCESS";
export const LOAD_ONE_PROJECT_FAILED="LOAD_ONE_PROJECT_FAILED";

/////////////////tasktypes////////////////////
export const LOAD_TASK_SUCCESS="LOAD_TASK_SUCCESS";
export const LOAD_TASK_FAILED="LOAD_TASK_FAILED";
export const ADD_TASK_SUCCESS="ADD_TASK_SUCCESS";
export const ADD_TASK_FAILED="ADD_TASK_FAILED";
export const EDIT_TASK_SUCCESS="EDIT_TASK_SUCCESS";
export const EDIT_TASK_FAILED="EDIT_TASK_FAILED";
export const DELETE_TASK_SUCCESS="DELETE_TASK_SUCCESS";
export const DELETE_TASK_FAILED="DELETE_TASK_FAILED";
export const LOAD_ALL_TASK_SUCCESS="LOAD_ALL_TASK_SUCCESS";
export const LOAD_ALL_TASK_FAILED="LOAD_ALL_TASK_FAILED";
export const DELETE_TALL_ASK_SUCCESS="DELETE_ALL_TASK_SUCCESS";
export const DELETE_ALL_TASK_FAILED="DELETE_ALL_TASK_FAILED"
export const GET_ALL_TASK_SUCCESS="GET_ALL_TASK_SUCCESS";
export const  GET_ALL_TASK_FAILED="GET_ALL_TASK_FAILED";

///////////editcollaborators/////
export const ADD_COLLAB_SUCCESS="ADD_COLLAB_SUCCESS";
export const DELETE_COLLAB_SUCCESS="DELETE_COLLAB_SUCCESS";
export const INIT_COLLAB_SUCCESS="INIT_COLLAB_SUCCESS";